---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
   cloudprovider.harvesterhci.io/ipam: dhcp
spec:
  ports:
    - port: 8080
      targetPort: 80
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer
